const DB_NAME = 'allo-contacts'; const STORE = 'contacts';
const $ = (id) => document.getElementById(id);
const els = { contacts:$('contacts'), empty:$('empty-state'), form:$('contact-form'), photo:$('contact-photo'), preview:$('photo-preview'), placeholder:$('photo-placeholder'), sizeButtons:[...document.querySelectorAll('[data-size]')] };
let activeContact = null; let pendingPhoto = null; let db;

function openDb() { return new Promise((resolve,reject) => { const request=indexedDB.open(DB_NAME,1); request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:'id'}); request.onsuccess=()=>{db=request.result;resolve();}; request.onerror=()=>reject(request.error); }); }
function getContacts() { return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll(); r.onsuccess=()=>resolve(r.result.sort((a,b)=>a.createdAt-b.createdAt)); r.onerror=()=>reject(r.error);}); }
function save(contact) { return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(contact); r.onsuccess=resolve; r.onerror=()=>reject(r.error);}); }
function remove(id) { return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id); r.onsuccess=resolve; r.onerror=()=>reject(r.error);}); }
function initials(name) { return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase(); }
function dialog(id) { $(id).showModal(); }
function close(id) { $(id).close(); }
function notice(message) { const el=$('notice'); el.textContent=message; el.classList.add('visible'); setTimeout(()=>el.classList.remove('visible'),2600); }

async function render() { const contacts=await getContacts(); els.contacts.replaceChildren(); els.empty.hidden=contacts.length!==0; contacts.forEach(contact=>{ const card=document.createElement('button'); card.className='contact-card'; card.type='button'; card.setAttribute('aria-label',`Appeler ${contact.name}`); if(contact.photo) { const image=document.createElement('img'); image.className='contact-photo'; image.src=contact.photo; image.alt=''; card.append(image); } else { const fallback=document.createElement('div'); fallback.className='contact-fallback'; fallback.textContent=initials(contact.name); fallback.setAttribute('aria-hidden','true'); card.append(fallback); } const label=document.createElement('span'); label.className='contact-label'; label.textContent=contact.name; card.append(label); const menu=document.createElement('button'); menu.className='card-menu'; menu.type='button'; menu.textContent='⋮'; menu.setAttribute('aria-label',`Gérer ${contact.name}`); menu.addEventListener('click',e=>{e.stopPropagation(); activeContact=contact; $('manage-title').textContent=contact.name; dialog('manage-dialog');}); card.append(menu); card.addEventListener('click',()=>showCall(contact)); els.contacts.append(card); }); }
function showCall(contact) { activeContact=contact; $('call-title').textContent=`J'appelle ${contact.name} ?`; $('call-phone').textContent=contact.phone; $('call-link').href=`tel:${contact.phone.replace(/[^+\d]/g,'')}`; const photo=$('call-photo'), avatar=$('call-avatar'); if(contact.photo) { photo.src=contact.photo; photo.hidden=false; avatar.hidden=true; } else { avatar.textContent=initials(contact.name); avatar.hidden=false; photo.hidden=true; } dialog('call-dialog'); }
function resetForm() { els.form.reset(); $('contact-id').value=''; pendingPhoto=null; els.preview.hidden=true; els.preview.removeAttribute('src'); els.placeholder.hidden=false; $('form-title').textContent='Nouveau contact'; }
function edit(contact) { close('manage-dialog'); resetForm(); $('form-title').textContent='Modifier le contact'; $('contact-id').value=contact.id; $('contact-name').value=contact.name; $('contact-phone').value=contact.phone; pendingPhoto=contact.photo||null; if(pendingPhoto){els.preview.src=pendingPhoto;els.preview.hidden=false;els.placeholder.hidden=true;} dialog('contact-dialog'); }
function setSize(size) { els.contacts.className=`contacts size-${size}`; localStorage.setItem('allo-size',size); els.sizeButtons.forEach(b=>b.classList.toggle('active',b.dataset.size===size)); }
function readFile(file) { return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);}); }

$('add-button').addEventListener('click',()=>{resetForm();dialog('contact-dialog');});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>close(b.dataset.close)));
$('call-cancel').addEventListener('click',()=>close('call-dialog'));
els.photo.addEventListener('change',async()=>{const file=els.photo.files[0];if(!file)return;pendingPhoto=await readFile(file);els.preview.src=pendingPhoto;els.preview.hidden=false;els.placeholder.hidden=true;});
els.form.addEventListener('submit',async e=>{e.preventDefault(); const id=$('contact-id').value; await save({id:id||crypto.randomUUID(),name:$('contact-name').value.trim(),phone:$('contact-phone').value.trim(),photo:pendingPhoto,createdAt:id?(activeContact?.createdAt||Date.now()):Date.now()}); close('contact-dialog'); await render(); notice('Contact enregistré.');});
$('edit-contact').addEventListener('click',()=>edit(activeContact)); $('delete-contact').addEventListener('click',async()=>{if(!activeContact)return; if(confirm(`Supprimer ${activeContact.name} ?`)){await remove(activeContact.id);close('manage-dialog');await render();notice('Contact supprimé.');}});
els.sizeButtons.forEach(b=>b.addEventListener('click',()=>setSize(b.dataset.size)));
$('export-button').addEventListener('click',async()=>{const data=await getContacts();const blob=new Blob([JSON.stringify({version:1,contacts:data},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sauvegarde-allo.json';a.click();URL.revokeObjectURL(a.href);notice('Sauvegarde téléchargée.');});
$('import-file').addEventListener('change',async()=>{const file=$('import-file').files[0];if(!file)return;try {const content=JSON.parse(await file.text());if(!Array.isArray(content.contacts))throw new Error();if(!confirm(`Importer ${content.contacts.length} contact(s) ? Les contacts existants seront conservés.`))return;for(const contact of content.contacts){if(contact.name&&contact.phone)await save({...contact,id:contact.id||crypto.randomUUID(),createdAt:contact.createdAt||Date.now()});}await render();notice('Liste importée.');}catch{notice('Ce fichier de sauvegarde est invalide.');}finally{$('import-file').value='';}});

async function start(){try{await openDb();setSize(localStorage.getItem('allo-size')||'medium');await render();if(localStorage.getItem('allo-update-requested')){localStorage.removeItem('allo-update-requested');notice('Version actualisée.');}}catch{notice("Le stockage local n'est pas disponible.");} if('serviceWorker' in navigator){let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!refreshing){refreshing=true;location.reload();}});const registration=await navigator.serviceWorker.register('./sw.js');$('update-button').addEventListener('click',()=>{if(registration.waiting){localStorage.setItem('allo-update-requested','1');registration.waiting.postMessage('skipWaiting');}});}}
start();
